services:
  - type: web
    name: shop-installment-tracker
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /
